- name: 
  hosts: local
  connection: local
  vars_files:
  - course.yaml
  tasks:
  - name: print the course details
    ansible.builtin.debug:
      msg: "course is  {{course}} for {{duration}}, trained by {{trainer}}"