- name: 
  hosts: local
  connection: local
  vars:
  - course: "Devops with AWS"
    duration: 120hrs
    trainer: "sai sandeep"
  tasks:
  - name: print the course details
    - course: "ansible"
    ansible.builtin.debug:
      msg: "course is  {{course}} for {{duration}}, trained by {{trainer}}"